import type { Artwork } from "@/lib/types";

export const artworks: Artwork[] = [
  {
    id: "ashen-001",
    slug: "ashen-operator",
    title: "Ashen Operator",
    creator: "@wale",
    twitterUrl: "https://x.com/wale",
    type: "1/1",
    status: "Added to gallery",
    variant: 0,
    upvotes: 482,
    downvotes: 18,
    submittedAt: "18m ago",
    description: "A signal runner built from the first body. One eye stays on the order.",
  },
  {
    id: "amber-002",
    slug: "amber-sentinel",
    title: "Amber Sentinel",
    creator: "@mossdoteth",
    twitterUrl: "https://x.com/mossdoteth",
    type: "Hats",
    status: "Community",
    variant: 1,
    upvotes: 336,
    downvotes: 22,
    submittedAt: "42m ago",
    description: "A broad helmet trait tested across all current ear shapes.",
  },
  {
    id: "static-003",
    slug: "static-eyes",
    title: "Static Eyes",
    creator: "@pixelfiend",
    twitterUrl: "https://x.com/pixelfiend",
    type: "Eyes",
    status: "In review",
    variant: 2,
    upvotes: 275,
    downvotes: 9,
    submittedAt: "1h ago",
    description: "Two-frame eye trait with a compact broadcast flicker.",
  },
  {
    id: "bone-004",
    slug: "bone-merchant",
    title: "Bone Merchant",
    creator: "@0xshade",
    twitterUrl: "https://x.com/0xshade",
    type: "1/1",
    status: "Community",
    variant: 3,
    upvotes: 219,
    downvotes: 31,
    submittedAt: "3h ago",
    description: "A wandering 1/1 carrying parts from an older collection.",
  },
  {
    id: "halo-005",
    slug: "broken-halo",
    title: "Broken Halo",
    creator: "@kola",
    twitterUrl: "https://x.com/kola",
    type: "Hats",
    status: "Added to gallery",
    variant: 4,
    upvotes: 198,
    downvotes: 12,
    submittedAt: "5h ago",
    description: "An overhead accessory with a split on the eastern edge.",
  },
  {
    id: "night-006",
    slug: "night-order",
    title: "Night Order",
    creator: "@faintsignal",
    twitterUrl: "https://x.com/faintsignal",
    type: "Special",
    status: "In review",
    variant: 5,
    upvotes: 142,
    downvotes: 15,
    submittedAt: "8h ago",
    description: "A full-body special treatment for the canonical base.",
  },
];

export const galleryTraits = [
  { name: "Crown of pins", type: "Head", variant: 1, creator: "@mossdoteth" },
  { name: "Static eyes", type: "Eyes", variant: 2, creator: "@pixelfiend" },
  { name: "Broken halo", type: "Accessory", variant: 4, creator: "@kola" },
  { name: "Night order", type: "Special", variant: 5, creator: "@faintsignal" },
  { name: "Amber room", type: "Background", variant: 6, creator: "@softproof" },
  { name: "Signal ears", type: "Accessory", variant: 7, creator: "@dotmatrix" },
];
